# Generated by Django 6.0.1 on 2026-08-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senmiridedriverrequest',
            old_name='commission',
            new_name='service_fee',
        ),
    ]
