# Generated by Django 6.0.1 on 2026-09-04 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Ride Pricing', max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SenmiRideDriverProfile',
            new_name='RideDriverProfile',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverrating',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverrating',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverrating',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverrequest',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverrequest',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverwallet',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='senmiridedriverwithdrawal',
            name='driver',
        ),
        
        migrations.CreateModel(
            name='RideBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideCommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_commission_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideCommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_commission_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='senmi_ride.ridecommissionpayment')),
            ],
        ),
        migrations.CreateModel(
            name='RideDriverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='SenmiRideDriverTracking',
            new_name='RideTracking',
        ),

        migrations.AlterModelOptions(
            name='ridetracking',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('pickup_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration_minutes', models.IntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=20)),
                ('commission_paid', models.BooleanField(default=False)),
                ('commission_paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_jobs', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_ratings', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='senmi_ride.riderequest')),
            ],
        ),
        migrations.AddField(
            model_name='ridecommissionpayment',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments', to='senmi_ride.riderequest'),
        ),
        migrations.AlterField(
            model_name='ridetracking',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='senmi_ride.riderequest'),
        ),
        migrations.CreateModel(
            name='RideWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SenmiRideDriverBank',
        ),
        migrations.DeleteModel(
            name='SenmiRideDriverRating',
        ),
        migrations.DeleteModel(
            name='SenmiRideDriverRequest',
        ),
        migrations.DeleteModel(
            name='SenmiRideDriverWallet',
        ),
        migrations.DeleteModel(
            name='SenmiRideDriverWithdrawal',
        ),
    ]
