# Generated by Django 6.0.1 on 2026-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedriverprofile',
            name='emergency_contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ridedriverprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ridedriverprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ridedriverprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
