# Generated by Django 6.1.1 on 2026-09-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0002_ridedriverprofile_emergency_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedriverprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ridedriverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ridedriverprofile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='ridedriverprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
