# Generated by Django 6.0.1 on 2026-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0002_ridepricingconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridecommissionpayment',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ridecommissionpayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank', 'Bank'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
