# Generated by Django 6.0.1 on 2026-09-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0003_ridecommissionpayment_access_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridewithdrawal',
            name='driver',
        ),
        migrations.RenameField(
            model_name='ridedriverwallet',
            old_name='balance',
            new_name='commission_balance',
        ),
        migrations.DeleteModel(
            name='RideBank',
        ),
        migrations.DeleteModel(
            name='RideWithdrawal',
        ),
    ]
