# Generated by Django 6.0.1 on 2026-09-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0004_remove_ridewithdrawal_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideDriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='senmi_ride.ridedriverprofile')),
            ],
        ),
    ]
