# Generated by Django 6.1.1 on 2026-10-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0004_ridesharetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedriverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
