# Generated by Django 6.0.1 on 2026-09-06 21:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0005_ridedriveravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridepricingconfig',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ridepricingconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ridepricingconfig',
            name='per_minute_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ridepricingconfig',
            name='service_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
    ]
