# Generated by Django 6.0.1 on 2026-09-07 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi_ride', '0006_alter_ridepricingconfig_base_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepricingconfig',
            name='premium_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='service_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
