# Generated by Django 6.0.1 on 2026-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpackage',
            old_name='commission',
            new_name='service_fee',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='commission',
            new_name='service_fee',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='recipient_code',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
