# Generated by Django 6.0.1 on 2026-03-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
