# Generated by Django 6.0.1 on 2026-03-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
