# Generated by Django 6.0.1 on 2026-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0002_alter_historicalpackage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackage',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
