# Generated by Django 6.0.1 on 2026-04-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0002_riderprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
