# Generated by Django 6.0.1 on 2026-08-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
