# Generated by Django 6.0.1 on 2026-03-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0002_remove_riderprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='rider_image_2',
            new_name='rider_with_bike_image',
        ),
    ]
