# Generated by Django 6.0.1 on 2026-03-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0003_rename_rider_image_2_riderprofile_rider_with_bike_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='rider_with_bike_image',
            new_name='rider_image_with_bike',
        ),
    ]
