# Generated by Django 6.0.1 on 2026-07-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0003_alter_historicalpackage_receiver_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
