# Generated by Django 6.0.1 on 2026-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0003_remove_user_deleted_at_remove_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='minimum_fare',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='per_minute_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='afternoon_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='evening_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='fuel_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='morning_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='night_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
    ]
