# Generated by Django 6.0.1 on 2026-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0003_alter_riderprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_credited',
            field=models.BooleanField(default=False),
        ),
    ]
