# Generated by Django 6.0.1 on 2026-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0003_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
