# Generated by Django 6.0.1 on 2026-04-06 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetracking',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='packagetracking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='senmi.package'),
        ),
    ]
