# Generated by Django 6.0.1 on 2026-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0004_alter_packagetracking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
