# Generated by Django 6.0.1 on 2026-08-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0004_withdrawal_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
