# Generated by Django 6.0.1 on 2026-09-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0004_pricingconfig_booking_fee_pricingconfig_minimum_fare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='booking_fee',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='minimum_fare',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='per_minute_rate',
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='afternoon_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='fuel_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=220, max_digits=10),
        ),
    ]
