# Generated by Django 6.0.1 on 2026-05-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0004_package_is_credited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_credited',
        ),
    ]
