# Generated by Django 6.0.1 on 2026-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0004_rename_rider_with_bike_image_riderprofile_rider_image_with_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rider_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
