# Generated by Django 6.0.1 on 2026-04-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0005_alter_package_delivery_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
    ]
