# Generated by Django 6.0.1 on 2026-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0005_withdrawal_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
