# Generated by Django 6.0.1 on 2026-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0005_remove_pricingconfig_booking_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='afternoon_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='evening_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=230, max_digits=10),
        ),
    ]
