# Generated by Django 6.0.1 on 2026-08-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0006_withdrawal_transfer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
    ]
