# Generated by Django 6.0.1 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0006_alter_pricingconfig_afternoon_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='evening_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='night_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
    ]
