# Generated by Django 6.0.1 on 2026-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0006_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
