# Generated by Django 6.0.1 on 2026-04-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0006_alter_package_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-package_id']},
        ),
    ]
