# Generated by Django 6.0.1 on 2026-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0006_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
