# Generated by Django 6.0.1 on 2026-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0007_riderprofile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='is_online',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
