# Generated by Django 6.0.1 on 2026-08-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0007_alter_withdrawal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
