# Generated by Django 6.0.1 on 2026-03-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0007_package_receiver_name_package_receiver_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='rider_image_with_bike',
            new_name='rider_image_with_vehicle',
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='rider_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
