# Generated by Django 6.0.1 on 2026-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0008_remove_riderprofile_is_online_riderprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='availability_mode',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
