# Generated by Django 6.0.1 on 2026-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0008_alter_pricingconfig_base_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='fuel_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=5),
        ),
    ]
