# Generated by Django 6.0.1 on 2026-03-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0009_riderprofile_rating_packagestatushistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
