# Generated by Django 6.0.1 on 2026-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0009_alter_pricingconfig_fuel_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='evening_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
