# Generated by Django 6.0.1 on 2026-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0009_riderprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='recipient_code',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transfer_code',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
