# Generated by Django 6.0.1 on 2026-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0010_alter_pricingconfig_evening_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='morning_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=230, max_digits=10),
        ),
    ]
