# Generated by Django 6.0.1 on 2026-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0010_riderprofile_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_type',
            field=models.CharField(choices=[('sender', 'Sender Pays'), ('receiver', 'Receiver Pays')], default='sender', max_length=10),
        ),
    ]
