# Generated by Django 6.0.1 on 2026-08-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0010_remove_withdrawal_recipient_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
