# Generated by Django 6.0.1 on 2026-05-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0010_remove_riderprofile_availability_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='last_seen',
        ),
    ]
