# Generated by Django 6.0.1 on 2026-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0011_withdrawal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
