# Generated by Django 6.0.1 on 2026-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0011_package_delivery_code_package_is_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='rider_image_with_vehicle',
            field=models.ImageField(blank=True, null=True, upload_to='riders/vehicle_images2/'),
        ),
    ]
