# Generated by Django 6.0.1 on 2026-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0011_alter_pricingconfig_base_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='morning_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
