# Generated by Django 6.0.1 on 2026-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0011_remove_riderprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rejection_reason2',
            field=models.TextField(blank=True),
        ),
    ]
