# Generated by Django 6.0.1 on 2026-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0012_withdrawal_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackage',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='rider_earning',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='service_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='rider_earning',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='service_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
