# Generated by Django 6.0.1 on 2026-05-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0012_riderprofile_rejection_reason2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='rejection_reason2',
        ),
    ]
