# Generated by Django 6.0.1 on 2026-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0012_alter_pricingconfig_morning_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=950, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=220, max_digits=10),
        ),
    ]
