# Generated by Django 6.0.1 on 2026-05-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0013_remove_riderprofile_rejection_reason2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('rider', 'Rider')], max_length=10),
        ),
    ]
