# Generated by Django 6.0.1 on 2026-09-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0013_alter_pricingconfig_base_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('support', 'Support'), ('customer', 'Customer'), ('rider', 'Rider'), ('ride_driver', 'Ride Driver')], max_length=50),
        ),
    ]
