# Generated by Django 6.0.1 on 2026-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='fuel_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='night_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
