# Generated by Django 6.0.1 on 2026-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
