# Generated by Django 6.0.1 on 2026-05-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0017_remove_user_fcm_token_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
