# Generated by Django 6.0.1 on 2026-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0018_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
