# Generated by Django 6.0.1 on 2026-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0019_package_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
