# Generated by Django 6.0.1 on 2026-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0020_package_failure_reason_riderprofile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('support', 'Support'), ('customer', 'Customer'), ('rider', 'Rider')], max_length=10),
        ),
    ]
