# Generated by Django 6.0.1 on 2026-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0022_package_refund_reason_package_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackage',
            name='refund_method',
            field=models.CharField(choices=[('manual', 'Manual Bank Transfer'), ('wallet', 'Wallet Refund')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='refund_method',
            field=models.CharField(choices=[('manual', 'Manual Bank Transfer'), ('wallet', 'Wallet Refund')], default='manual', max_length=20),
        ),
    ]
