# Generated by Django 6.0.1 on 2026-06-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0023_historicalpackage_refund_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageStatusHistory',
        ),
    ]
