# Generated by Django 6.0.1 on 2026-06-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0024_delete_packagestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackage',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='payment_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
