# Generated by Django 6.0.1 on 2026-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0026_pricingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_fee',
            field=models.IntegerField(default=920),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='evening_multiplier',
            field=models.FloatField(default=1.3),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='night_multiplier',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.IntegerField(default=170),
        ),
    ]
