# Generated by Django 6.0.1 on 2026-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0027_alter_pricingconfig_base_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='afternoon_multiplier',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_fee',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='morning_multiplier',
            field=models.FloatField(default=1.1),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.IntegerField(default=181),
        ),
    ]
