# Generated by Django 6.0.1 on 2026-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0028_alter_pricingconfig_afternoon_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_km_rate',
            field=models.IntegerField(default=220),
        ),
    ]
