# Generated by Django 6.0.1 on 2026-06-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0029_alter_pricingconfig_per_km_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'All'), ('riders', 'Riders'), ('customers', 'Customers'), ('single', 'Single User')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
