# Generated by Django 6.0.1 on 2026-06-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0031_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='afternoon_multiplier',
            field=models.FloatField(default=1.1),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='evening_multiplier',
            field=models.FloatField(default=1.1),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='morning_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='night_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
