# Generated by Django 6.0.1 on 2026-06-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0032_alter_pricingconfig_afternoon_multiplier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingConfig',
        ),
    ]
