# Generated by Django 6.0.1 on 2026-06-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senmi', '0033_delete_pricingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Pricing', max_length=50)),
                ('base_fee', models.IntegerField(default=1000)),
                ('per_km_rate', models.IntegerField(default=220)),
                ('fuel_multiplier', models.FloatField(default=1.2)),
                ('morning_multiplier', models.FloatField(default=1.0)),
                ('afternoon_multiplier', models.FloatField(default=1.1)),
                ('evening_multiplier', models.FloatField(default=1.1)),
                ('night_multiplier', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
